

// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.com/).
// Created by Simon Hughes (https://about.me/simon.hughes).
//
// Do not make changes directly to this file - edit the template instead.
//
// The following connection settings were used to generate this file:
//     Configuration file:     "ReversePOCO\App.config"
//     Connection String Name: "BondModelDb"
//     Connection String:      "User Id=BOND;password=**zapped**;;Data Source=10.10.7.30:1521/bond"
// ------------------------------------------------------------------------------------------------

// -----------------------------------------------------------------------------------------
// Failed to read database schema in LoadTables() - ORA-00923: FROM keyword not found where expected
// -----------------------------------------------------------------------------------------


// -----------------------------------------------------------------------------------------
// Failed to read database schema for stored procedures - ORA-00923: FROM keyword not found where expected
// -----------------------------------------------------------------------------------------

